Repository domidemps/popote, pull requests merged in 2020-12, with the labels that each got.

#21 Update README
  README.md
Labels: documentation

#23 [Front] #7 - Login interface
  package.json
  python/api/users.py
  src/actions/user.jsx
  src/containers/login/LoginView.jsx
  src/containers/utils/PrivateRoute.jsx
  src/index.jsx
  src/reducers/index.jsx
  src/reducers/user.jsx
  src/root.jsx
  src/store/configureStore.jsx
  src/styles/breakpoints.js
  src/styles/main.css
  src/styles/material_ui_raw_theme_file.jsx
  src/styles/media.js
  webpack.config.js
  yarn.lock
Labels: enhancement, frontend

#26 Favicon
  src/index.ejs
Labels: design, frontend

#27 [Dependabot alert] Resolve node-forge vulnerability
  yarn.lock
Labels: dependencies

#28 [Backend] Update GET users/me to return useful info
  python/api/users.py
  python/security/oauth.py
Labels: backend, enhancement

#29 [Backend][Fix] Fix type hints for read_users
  python/api/users.py
Labels: backend, bug
